// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package manualchargedb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// User-asserted home/work/third-party charge sessions not captured by the Tesla Fleet API. Owned by internal/manualcharge; no other module reads this table directly. Mutable table: full CRUD via Writer port (users correct hand-typed entries). No cross-module FK on account_id or tesla_id (ai/architecture.md §2). No raw_data JSONB column: user-typed data has no vendor payload to preserve (ai/go-conventions.md §persistence, design D5).
type ManualChargeEntry struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TeslaID         int64
	Vin             string
	ChargedOn       pgtype.Date
	EnergyAddedKwh  pgtype.Numeric
	Price           pgtype.Numeric
	Currency        string
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	StartBatteryPct pgtype.Int2
	EndBatteryPct   pgtype.Int2
	ChargingType    pgtype.Text
	LocationKind    string
	LocationLabel   pgtype.Text
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
