// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package chargingdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one

INSERT INTO manual_charge_entries (
    account_id,
    tesla_id,
    vin,
    charged_on,
    energy_added_kwh,
    price,
    currency,
    started_at,
    ended_at,
    start_battery_pct,
    end_battery_pct,
    charging_type,
    location_kind,
    location_label,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, account_id, tesla_id, vin, charged_on, energy_added_kwh, price, currency, started_at, ended_at, start_battery_pct, end_battery_pct, charging_type, location_kind, location_label, notes, created_at, updated_at
`

type CreateEntryParams struct {
	AccountID       uuid.UUID
	TeslaID         int64
	Vin             string
	ChargedOn       pgtype.Date
	EnergyAddedKwh  pgtype.Numeric
	Price           pgtype.Numeric
	Currency        string
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	StartBatteryPct pgtype.Int2
	EndBatteryPct   pgtype.Int2
	ChargingType    pgtype.Text
	LocationKind    string
	LocationLabel   pgtype.Text
	Notes           pgtype.Text
}

// Queries for the manualcharge module. sqlc generates package `manualchargedb` from
// these against the schema in migrations/. No other module may import manualchargedb
// (module-scoped DB access — ai/architecture.md §2, ai/go-conventions.md §persistence).
// Unlike telemetry's append-only tables, manual_charge_entries is mutable: all five
// operations (create, update, delete, list-by-vehicle, list-by-account) are live CRUD.
// Insert a new user-asserted charge entry. All required fields are non-nullable params;
// optional fields use nullable params (sqlc maps them to pgtype nullable types via the
// schema column types). RETURNING * hands back the server-assigned id, created_at, and
// updated_at so the gateway can display the stored entry without a second round-trip.
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (ManualChargeEntry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AccountID,
		arg.TeslaID,
		arg.Vin,
		arg.ChargedOn,
		arg.EnergyAddedKwh,
		arg.Price,
		arg.Currency,
		arg.StartedAt,
		arg.EndedAt,
		arg.StartBatteryPct,
		arg.EndBatteryPct,
		arg.ChargingType,
		arg.LocationKind,
		arg.LocationLabel,
		arg.Notes,
	)
	var i ManualChargeEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TeslaID,
		&i.Vin,
		&i.ChargedOn,
		&i.EnergyAddedKwh,
		&i.Price,
		&i.Currency,
		&i.StartedAt,
		&i.EndedAt,
		&i.StartBatteryPct,
		&i.EndBatteryPct,
		&i.ChargingType,
		&i.LocationKind,
		&i.LocationLabel,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM manual_charge_entries
WHERE id = $1
  AND account_id = $2
`

type DeleteEntryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

// Delete a charge entry scoped to the caller's own account. The double-scope
// (id AND account_id) means a user cannot delete another tenant's entry even
// if they somehow obtain a valid entry UUID — cross-tenant deletes are blocked
// at the SQL level (design D4, intentional double-scope guard).
func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.Exec(ctx, deleteEntry, arg.ID, arg.AccountID)
	return err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT id, account_id, tesla_id, vin, charged_on, energy_added_kwh, price, currency, started_at, ended_at, start_battery_pct, end_battery_pct, charging_type, location_kind, location_label, notes, created_at, updated_at FROM manual_charge_entries
WHERE account_id = $1
ORDER BY charged_on DESC
LIMIT $2
`

type ListEntriesByAccountParams struct {
	AccountID  uuid.UUID
	LimitCount int32
}

// Return all entries for a given account across all vehicles, ordered newest charged
// day first, limited to limit_count rows. Uses idx_manual_charge_entries_account_time
// (account_id, charged_on DESC): account_id is the single WHERE predicate and
// charged_on DESC matches the ORDER BY, eliminating a sort step (design D3, Read path 2).
func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]ManualChargeEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount, arg.AccountID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualChargeEntry
	for rows.Next() {
		var i ManualChargeEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.Vin,
			&i.ChargedOn,
			&i.EnergyAddedKwh,
			&i.Price,
			&i.Currency,
			&i.StartedAt,
			&i.EndedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.ChargingType,
			&i.LocationKind,
			&i.LocationLabel,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByVehicle = `-- name: ListEntriesByVehicle :many
SELECT id, account_id, tesla_id, vin, charged_on, energy_added_kwh, price, currency, started_at, ended_at, start_battery_pct, end_battery_pct, charging_type, location_kind, location_label, notes, created_at, updated_at FROM manual_charge_entries
WHERE account_id = $1
  AND tesla_id = $2
ORDER BY charged_on DESC
LIMIT $3
`

type ListEntriesByVehicleParams struct {
	AccountID  uuid.UUID
	TeslaID    int64
	LimitCount int32
}

// Return entries for a specific vehicle within an account, ordered newest charged
// day first, limited to limit_count rows. Uses idx_manual_charge_entries_vehicle_time
// (account_id, tesla_id, charged_on DESC): account_id prunes to the tenant, tesla_id
// further narrows to one vehicle, and the DESC column means the ORDER BY is satisfied
// by the index directly — no sort step required (design D3, Read path 1).
func (q *Queries) ListEntriesByVehicle(ctx context.Context, arg ListEntriesByVehicleParams) ([]ManualChargeEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByVehicle, arg.AccountID, arg.TeslaID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualChargeEntry
	for rows.Next() {
		var i ManualChargeEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.Vin,
			&i.ChargedOn,
			&i.EnergyAddedKwh,
			&i.Price,
			&i.Currency,
			&i.StartedAt,
			&i.EndedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.ChargingType,
			&i.LocationKind,
			&i.LocationLabel,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByVehicleBetween = `-- name: ListEntriesByVehicleBetween :many
SELECT id, account_id, tesla_id, vin, charged_on, energy_added_kwh, price, currency, started_at, ended_at, start_battery_pct, end_battery_pct, charging_type, location_kind, location_label, notes, created_at, updated_at FROM manual_charge_entries
WHERE account_id = $1
  AND tesla_id = $2
  AND charged_on BETWEEN $3 AND $4
ORDER BY charged_on DESC
`

type ListEntriesByVehicleBetweenParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	FromDate  pgtype.Date
	ToDate    pgtype.Date
}

// Return entries for a specific vehicle within an account whose charged_on falls
// within [@from_date, @to_date], inclusive of both bounds, ordered newest charged
// day first. Uses idx_manual_charge_entries_vehicle_time (account_id, tesla_id,
// charged_on DESC) as a single index range scan: account_id and tesla_id prune to
// the tenant and vehicle, charged_on BETWEEN walks the range, and the DESC column
// order satisfies ORDER BY with no separate sort step (design D3). No LIMIT: the
// caller-supplied [from, to] window is the safety bound, not a row count
// (design D1, roadmap D9).
func (q *Queries) ListEntriesByVehicleBetween(ctx context.Context, arg ListEntriesByVehicleBetweenParams) ([]ManualChargeEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByVehicleBetween,
		arg.AccountID,
		arg.TeslaID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualChargeEntry
	for rows.Next() {
		var i ManualChargeEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.Vin,
			&i.ChargedOn,
			&i.EnergyAddedKwh,
			&i.Price,
			&i.Currency,
			&i.StartedAt,
			&i.EndedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.ChargingType,
			&i.LocationKind,
			&i.LocationLabel,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByVehicleUpdatedSince = `-- name: ListEntriesByVehicleUpdatedSince :many
SELECT id, account_id, tesla_id, vin, charged_on, energy_added_kwh, price, currency, started_at, ended_at, start_battery_pct, end_battery_pct, charging_type, location_kind, location_label, notes, created_at, updated_at FROM manual_charge_entries
WHERE account_id = $1
  AND tesla_id = $2
  AND updated_at >= $3
ORDER BY charged_on DESC
`

type ListEntriesByVehicleUpdatedSinceParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	Since     pgtype.Timestamptz
}

// Return entries for a specific vehicle within an account whose updated_at is at or
// after @since, ordered newest charged day first. Reuses
// idx_manual_charge_entries_vehicle_time (account_id, tesla_id, charged_on DESC):
// account_id and tesla_id are satisfied as leading equality predicates in the same
// range scan the other vehicle-scoped queries use; updated_at >= @since is a residual
// filter within that scan (no new index — this table is small and user-write-driven,
// unlike the append-only, high-volume tables). No LIMIT: @since itself bounds the
// result (RM29-analytics-add-vehicle-metrics design D3, specs/manual-charge-log/spec.md
// "List entries by vehicle updated since a given instant").
func (q *Queries) ListEntriesByVehicleUpdatedSince(ctx context.Context, arg ListEntriesByVehicleUpdatedSinceParams) ([]ManualChargeEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByVehicleUpdatedSince, arg.AccountID, arg.TeslaID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualChargeEntry
	for rows.Next() {
		var i ManualChargeEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.Vin,
			&i.ChargedOn,
			&i.EnergyAddedKwh,
			&i.Price,
			&i.Currency,
			&i.StartedAt,
			&i.EndedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.ChargingType,
			&i.LocationKind,
			&i.LocationLabel,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mirrorChargeSession = `-- name: MirrorChargeSession :exec
INSERT INTO charge_sessions (
    account_id, vin, tesla_id, session_id,
    charge_start_date_time, charge_stop_date_time,
    site_location_name, energy_kwh, total_cost, currency, is_paid
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10, $11
)
ON CONFLICT (account_id, session_id) DO UPDATE SET
    energy_kwh = EXCLUDED.energy_kwh,
    total_cost = EXCLUDED.total_cost,
    currency   = EXCLUDED.currency,
    is_paid    = EXCLUDED.is_paid,
    tesla_id   = EXCLUDED.tesla_id,
    updated_at = now()
`

type MirrorChargeSessionParams struct {
	AccountID           uuid.UUID
	Vin                 string
	TeslaID             pgtype.Int8
	SessionID           int64
	ChargeStartDateTime pgtype.Timestamptz
	ChargeStopDateTime  pgtype.Timestamptz
	SiteLocationName    string
	EnergyKwh           pgtype.Float8
	TotalCost           pgtype.Float8
	Currency            pgtype.Text
	IsPaid              pgtype.Bool
}

// Upsert one Supercharger session's mirrorable subset. Called once per session, in
// one transaction, by SessionWriter.MirrorSessions.
//
// LOAD-BEARING: start_battery_pct, end_battery_pct, battery_pct_source,
// start_battery_pct_est and end_battery_pct_est are ABSENT from both the INSERT
// column list and the ON CONFLICT DO UPDATE SET clause. They are human-owned; the
// nightly sync must never write, clear or overwrite one. Unlike
// telemetry.UpsertSuperchargerSession — which relies on this comment alone —
// charging.SessionMirror has no field for them either, so binding one here would not
// even compile (design.md D6). Do NOT "complete the pattern" by adding them.
//
// THE REFRESH SET IS NOT A JUDGEMENT CALL. It is telemetry's own ON CONFLICT DO
// UPDATE SET, minus raw_data (a column this table does not carry): energy_kwh,
// total_cost, currency, is_paid, tesla_id, updated_at. Everything else mirrored —
// charge_start_date_time, charge_stop_date_time, site_location_name, created_at — is
// write-once at the source, so it is write-once here. site_location_name in
// particular is NOT refreshed because telemetry does not refresh it, not because a
// site name was judged unlikely to change (design.md D1's rule: a mirrored column
// gets exactly its source column's write semantics).
//
// NO WHERE PREDICATE on the DO UPDATE, deliberately (design.md D6). An earlier draft
// carried WHERE charge_sessions.tesla_id IS DISTINCT FROM EXCLUDED.tesla_id so an
// unchanged row was not rewritten. With five refreshable columns that predicate would
// have to name all five, and a future column added to the SET but forgotten in the
// WHERE would silently stop advancing updated_at, with nothing in this project able
// to catch it. Telemetry's own upsert has no such predicate either. Consequence:
// updated_at here means "the last mirror pass touched this row" — exactly what
// supercharger_sessions.updated_at means — and is NOT a "this row's data changed"
// signal on either side.
func (q *Queries) MirrorChargeSession(ctx context.Context, arg MirrorChargeSessionParams) error {
	_, err := q.db.Exec(ctx, mirrorChargeSession,
		arg.AccountID,
		arg.Vin,
		arg.TeslaID,
		arg.SessionID,
		arg.ChargeStartDateTime,
		arg.ChargeStopDateTime,
		arg.SiteLocationName,
		arg.EnergyKwh,
		arg.TotalCost,
		arg.Currency,
		arg.IsPaid,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE manual_charge_entries
SET
    charged_on        = $1,
    energy_added_kwh  = $2,
    price             = $3,
    currency          = $4,
    started_at        = $5,
    ended_at          = $6,
    start_battery_pct = $7,
    end_battery_pct   = $8,
    charging_type     = $9,
    location_kind     = $10,
    location_label    = $11,
    notes             = $12,
    updated_at        = now()
WHERE id = $13
  AND account_id = $14
RETURNING id, account_id, tesla_id, vin, charged_on, energy_added_kwh, price, currency, started_at, ended_at, start_battery_pct, end_battery_pct, charging_type, location_kind, location_label, notes, created_at, updated_at
`

type UpdateEntryParams struct {
	ChargedOn       pgtype.Date
	EnergyAddedKwh  pgtype.Numeric
	Price           pgtype.Numeric
	Currency        string
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	StartBatteryPct pgtype.Int2
	EndBatteryPct   pgtype.Int2
	ChargingType    pgtype.Text
	LocationKind    string
	LocationLabel   pgtype.Text
	Notes           pgtype.Text
	ID              uuid.UUID
	AccountID       uuid.UUID
}

// Update mutable fields of an existing charge entry. The WHERE clause scopes to
// (id, account_id) so a user cannot update another tenant's entry even with a valid
// UUID — cross-tenant mutation is blocked at the SQL level (design D4).
// Immutable columns (id, account_id, tesla_id, vin, created_at) are never touched.
// updated_at is refreshed to now() on every successful update.
func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (ManualChargeEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ChargedOn,
		arg.EnergyAddedKwh,
		arg.Price,
		arg.Currency,
		arg.StartedAt,
		arg.EndedAt,
		arg.StartBatteryPct,
		arg.EndBatteryPct,
		arg.ChargingType,
		arg.LocationKind,
		arg.LocationLabel,
		arg.Notes,
		arg.ID,
		arg.AccountID,
	)
	var i ManualChargeEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TeslaID,
		&i.Vin,
		&i.ChargedOn,
		&i.EnergyAddedKwh,
		&i.Price,
		&i.Currency,
		&i.StartedAt,
		&i.EndedAt,
		&i.StartBatteryPct,
		&i.EndBatteryPct,
		&i.ChargingType,
		&i.LocationKind,
		&i.LocationLabel,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
