// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package telemetrydb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PollAttempt struct {
	ID                uuid.UUID
	PolledByAccountID uuid.UUID
	TeslaID           int64
	AttemptedAt       pgtype.Timestamptz
	Outcome           string
	Reason            string
	// Correlates every vehicle's attempt row from one app.ProcessVehicleData invocation. Generated once per invocation by internal/app (uuid.New()) and passed down via telemetry.RunContext (design.md D5). NULL on every row written before this migration — that run's identity was never recorded and is not recoverable; never backfilled, never will be.
	RunID pgtype.UUID
	// What triggered the run that wrote this attempt: scheduler (the nightly poller, including cmd/poller --once) or api (a future manual re-run, RM29 tier 8, parked). NOT NULL DEFAULT 'scheduler' backfills every pre-migration row correctly, since no non-scheduler entry point existed before this tier. Guarded by the typed Go constant telemetry.TriggeredBy — no DB CHECK (design.md D1/D7).
	TriggeredBy string
}

// One row per app.ProcessVehicleData invocation (nightly scheduler or cmd/poller --once), written once by telemetry.RunWriter.RecordRun after the whole run completes -- success or the step-1 whole-cycle-failure path alike (RM36-telemetry-add-poll-runs design D1/D3/D6). Reproduces the poller's per-cycle log line (telemetry.LogCycle) as a queryable row (design D5/D7).
type PollRun struct {
	// The invocation's identity, generated once by internal/app (uuid.New()) and shared with every poll_attempts row that invocation wrote via RunContext.RunID. No FK to poll_attempts -- see this file's header (design D2).
	RunID uuid.UUID
	// scheduler (the nightly poller, including cmd/poller --once) or api (the parked manual-rerun API, RM29 tier 8) -- same domain and same no-CHECK reasoning as poll_attempts.triggered_by (design D4).
	TriggeredBy       string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	DurationSeconds   float64
	AccountsAttempted int32
	AccountsSucceeded int32
	// Accounts that hit one of the two whole-account short-circuits in collectAccount: AccessTokenFor failure, or the up-front ListVehicles call returning tesla.ErrUnauthorized (roadmap D4). No other failure mode counts here; accounts_succeeded = accounts_attempted - accounts_failed.
	AccountsFailed        int32
	VehiclesAttempted     int32
	VehiclesSucceeded     int32
	FailuresAsleepTimeout int32
	FailuresUnauthorized  int32
	FailuresApiError      int32
	// Every call telemetry made to tesla.VehicleService during this run (ListVehicles, WakeUp, VehicleData, ChargingHistory), counted by an internal counting decorator regardless of whether the call succeeded or failed (roadmap D2, design D9/D10) -- a rejected request still spends a request against Tesla's API.
	TeslaApiCalls            int32
	ChargingSessionsUpserted int32
	ChargingFetchFailures    int32
	ConfigCaptureFailures    int32
}

// Tesla-billed Supercharger and DC fast-charging sessions per account. Covers sessions returned by GET /api/1/dx/charging/history only (no home/AC charging). The Tesla API itself carries no battery-percentage field; start_battery_pct/end_battery_pct/battery_pct_source are a human-owned verification/override channel, and start_battery_pct_est/end_battery_pct_est are a frozen write-once snapshot of the estimate at verification time (both added by RM27 tier 1, MAG-14) -- all five excluded from the nightly UPSERT so a verified value or its snapshot is never silently overwritten (R3). Owned by internal/telemetry; no other module reads this table directly. UPSERT on session_id (not append-only): billing state is mutable post-session.
type SuperchargerHistory struct {
	ID                  uuid.UUID
	SessionID           int64
	Vin                 string
	TeslaID             int64
	SiteLocationName    string
	CountryCode         string
	ChargeStartDateTime pgtype.Timestamptz
	ChargeStopDateTime  pgtype.Timestamptz
	UnlatchDateTime     pgtype.Timestamptz
	BillingType         string
	VehicleMakeType     string
	EnergyKwh           pgtype.Float8
	TotalCost           pgtype.Float8
	Currency            pgtype.Text
	IsPaid              pgtype.Bool
	RawData             []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	// Human-verified/override battery % at charge start (0-100). NULL = no override; reads fall back to internal/battery's on-read estimate (R5). Excluded from UpsertSuperchargerHistory's INSERT and ON CONFLICT DO UPDATE SET -- never auto-written by the nightly poller (R3).
	StartBatteryPct pgtype.Int2
	// Human-verified/override battery % at charge end (0-100). Same NULL convention and the same R3 write-protection as start_battery_pct.
	EndBatteryPct pgtype.Int2
	// Why start/end_battery_pct are set: user_verified (verification UI, out of scope this tier) or polled (future measured-SOC alternative, logged to the backlog, not implemented). NULL means no override exists. Never 'estimated' -- that state is computed on read by internal/battery and is never persisted here (R6).
	BatteryPctSource pgtype.Text
}

type VehicleSnapshot struct {
	ID                    uuid.UUID
	AccountID             pgtype.UUID
	TeslaID               int64
	CapturedAt            pgtype.Timestamptz
	RawData               []byte
	BatteryLevelPct       int32
	BatteryRangeKm        float64
	ChargingState         string
	ChargeLimitSocPct     int32
	OdometerKm            float64
	InsideTempC           float64
	OutsideTempC          float64
	Locked                bool
	SentryMode            pgtype.Bool
	CarVersion            string
	ChargeEnergyAddedKwh  pgtype.Float8
	ChargerPowerKw        pgtype.Int4
	ChargerVoltageV       pgtype.Int4
	ChargerActualCurrentA pgtype.Int4
	UsableBatteryLevelPct pgtype.Int4
	MaxRangeChargeCounter pgtype.Int4
	TpmsPressureFlPsi     pgtype.Float4
	TpmsPressureFrPsi     pgtype.Float4
	TpmsPressureRlPsi     pgtype.Float4
	TpmsPressureRrPsi     pgtype.Float4
	CapturedDate          pgtype.Date
	UpdatedAt             pgtype.Timestamptz
}
