// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package telemetrydb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PollAttempt struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	TeslaID     int64
	AttemptedAt pgtype.Timestamptz
	Outcome     string
	Reason      string
}

// Tesla-billed Supercharger and DC fast-charging sessions per account. Covers sessions returned by GET /api/1/dx/charging/history only (no home/AC charging, no battery percentage). Owned by internal/telemetry; no other module reads this table directly. UPSERT on session_id (not append-only): billing state is mutable post-session.
type SuperchargerSession struct {
	ID                  uuid.UUID
	SessionID           int64
	AccountID           uuid.UUID
	Vin                 string
	TeslaID             pgtype.Int8
	SiteLocationName    string
	CountryCode         string
	ChargeStartDateTime pgtype.Timestamptz
	ChargeStopDateTime  pgtype.Timestamptz
	UnlatchDateTime     pgtype.Timestamptz
	BillingType         string
	VehicleMakeType     string
	EnergyKwh           pgtype.Float8
	TotalCost           pgtype.Float8
	Currency            pgtype.Text
	IsPaid              pgtype.Bool
	RawData             []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type VehicleSnapshot struct {
	ID                     uuid.UUID
	AccountID              uuid.UUID
	TeslaID                int64
	CapturedAt             pgtype.Timestamptz
	RawData                []byte
	BatteryLevelPct        int32
	BatteryRangeKm         float64
	ChargingState          string
	ChargeLimitSocPct      int32
	OdometerKm             float64
	InsideTempC            float64
	OutsideTempC           float64
	Locked                 bool
	SentryMode             pgtype.Bool
	CarVersion             string
	ChargeEnergyAddedKwh   pgtype.Float8
	ChargerPowerKw         pgtype.Int4
	ChargerVoltageV        pgtype.Int4
	ChargerActualCurrentA  pgtype.Int4
	UsableBatteryLevelPct  pgtype.Int4
	MaxRangeChargeCounter  pgtype.Int4
	TpmsPressureFlPsi      pgtype.Float4
	TpmsPressureFrPsi      pgtype.Float4
	TpmsPressureRlPsi      pgtype.Float4
	TpmsPressureRrPsi      pgtype.Float4
	CapturedDate           pgtype.Date
	UpdatedAt              pgtype.Timestamptz
	DistanceTraveledKmCalc pgtype.Float8
	BatteryUsedPctCalc     pgtype.Int4
	KmPerPctCalc           pgtype.Float8
	EstimatedRangeKmCalc   pgtype.Float8
	DaysSpannedCalc        pgtype.Int4
}
