// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package telemetrydb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const chargeGapDatesByVehicleBetween = `-- name: ChargeGapDatesByVehicleBetween :many
SELECT gap_date FROM charge_gaps
WHERE account_id = $1
  AND tesla_id   = $2
  AND gap_date   >= $3
  AND gap_date   <= $4
`

type ChargeGapDatesByVehicleBetweenParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	Start     pgtype.Date
	EndDate   pgtype.Date
}

// Return every stored charge_gaps date for one vehicle (within one account)
// in the closed range [start, end]. Used ONLY by
// GapWriter.ReconcileWindow's internal bookkeeping to compute which
// previously-stored days are no longer in the caller's flagged set (and so
// must be deleted) -- not a public read port, not consumed outside this
// module's own write path. Single-column SELECT (gap_date only): the caller
// already has every other field it needs for any date it decides to keep
// (it is re-upserting from its own freshly-computed flagged set, never
// reading this table's other columns back).
//
// Index reuse (design.md Index Plan, Read path 1): served directly by
// charge_gaps_account_tesla_date_unique's own (account_id, tesla_id, gap_date)
// index as a single contiguous forward range scan -- no new index.
func (q *Queries) ChargeGapDatesByVehicleBetween(ctx context.Context, arg ChargeGapDatesByVehicleBetweenParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, chargeGapDatesByVehicleBetween,
		arg.AccountID,
		arg.TeslaID,
		arg.Start,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var gap_date pgtype.Date
		if err := rows.Scan(&gap_date); err != nil {
			return nil, err
		}
		items = append(items, gap_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChargeGap = `-- name: DeleteChargeGap :exec
DELETE FROM charge_gaps
WHERE account_id = $1
  AND tesla_id   = $2
  AND gap_date   = $3
`

type DeleteChargeGapParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	GapDate   pgtype.Date
}

// Delete one charge_gaps row scoped to (account_id, tesla_id, gap_date) -- a
// point delete served by the charge_gaps_account_tesla_date_unique
// constraint's own index (design.md Index Plan, Read path 1). Called by
// GapWriter.ReconcileWindow for every previously-stored day in the window
// that is no longer present in the caller's freshly-computed flagged set
// (roadmap D7b).
func (q *Queries) DeleteChargeGap(ctx context.Context, arg DeleteChargeGapParams) error {
	_, err := q.db.Exec(ctx, deleteChargeGap, arg.AccountID, arg.TeslaID, arg.GapDate)
	return err
}

const insertPollAttempt = `-- name: InsertPollAttempt :exec
INSERT INTO poll_attempts (
    account_id, tesla_id, attempted_at, outcome, reason
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertPollAttemptParams struct {
	AccountID   uuid.UUID
	TeslaID     int64
	AttemptedAt pgtype.Timestamptz
	Outcome     string
	Reason      string
}

// Record one attempt per (vehicle, run), success or failure. outcome is
// success|failure; reason is ok|asleep-timeout|unauthorized|api-error.
func (q *Queries) InsertPollAttempt(ctx context.Context, arg InsertPollAttemptParams) error {
	_, err := q.db.Exec(ctx, insertPollAttempt,
		arg.AccountID,
		arg.TeslaID,
		arg.AttemptedAt,
		arg.Outcome,
		arg.Reason,
	)
	return err
}

const insertVehicleSnapshot = `-- name: InsertVehicleSnapshot :exec

INSERT INTO vehicle_snapshots (
    account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14,
    $15, $16, $17,
    $18, $19,
    $20,
    $21, $22, $23, $24,
    $25,
    $26, $27, $28,
    $29, $30
)
ON CONFLICT (account_id, tesla_id, captured_date) DO UPDATE SET
    captured_at               = EXCLUDED.captured_at,
    raw_data                  = EXCLUDED.raw_data,
    battery_level_pct         = EXCLUDED.battery_level_pct,
    battery_range_km          = EXCLUDED.battery_range_km,
    charging_state            = EXCLUDED.charging_state,
    charge_limit_soc_pct      = EXCLUDED.charge_limit_soc_pct,
    odometer_km               = EXCLUDED.odometer_km,
    inside_temp_c              = EXCLUDED.inside_temp_c,
    outside_temp_c             = EXCLUDED.outside_temp_c,
    locked                     = EXCLUDED.locked,
    sentry_mode                = EXCLUDED.sentry_mode,
    car_version                = EXCLUDED.car_version,
    charge_energy_added_kwh    = EXCLUDED.charge_energy_added_kwh,
    charger_power_kw           = EXCLUDED.charger_power_kw,
    charger_voltage_v          = EXCLUDED.charger_voltage_v,
    charger_actual_current_a   = EXCLUDED.charger_actual_current_a,
    usable_battery_level_pct   = EXCLUDED.usable_battery_level_pct,
    max_range_charge_counter   = EXCLUDED.max_range_charge_counter,
    tpms_pressure_fl_psi       = EXCLUDED.tpms_pressure_fl_psi,
    tpms_pressure_fr_psi       = EXCLUDED.tpms_pressure_fr_psi,
    tpms_pressure_rl_psi       = EXCLUDED.tpms_pressure_rl_psi,
    tpms_pressure_rr_psi       = EXCLUDED.tpms_pressure_rr_psi,
    distance_traveled_km_calc  = EXCLUDED.distance_traveled_km_calc,
    battery_used_pct_calc      = EXCLUDED.battery_used_pct_calc,
    km_per_pct_calc            = EXCLUDED.km_per_pct_calc,
    estimated_range_km_calc    = EXCLUDED.estimated_range_km_calc,
    days_spanned_calc          = EXCLUDED.days_spanned_calc,
    updated_at                 = now()
`

type InsertVehicleSnapshotParams struct {
	AccountID              uuid.UUID
	TeslaID                int64
	CapturedAt             pgtype.Timestamptz
	RawData                []byte
	BatteryLevelPct        int32
	BatteryRangeKm         float64
	ChargingState          string
	ChargeLimitSocPct      int32
	OdometerKm             float64
	InsideTempC            float64
	OutsideTempC           float64
	Locked                 bool
	SentryMode             pgtype.Bool
	CarVersion             string
	ChargeEnergyAddedKwh   pgtype.Float8
	ChargerPowerKw         pgtype.Int4
	ChargerVoltageV        pgtype.Int4
	ChargerActualCurrentA  pgtype.Int4
	UsableBatteryLevelPct  pgtype.Int4
	MaxRangeChargeCounter  pgtype.Int4
	TpmsPressureFlPsi      pgtype.Float4
	TpmsPressureFrPsi      pgtype.Float4
	TpmsPressureRlPsi      pgtype.Float4
	TpmsPressureRrPsi      pgtype.Float4
	CapturedDate           pgtype.Date
	DistanceTraveledKmCalc pgtype.Float8
	BatteryUsedPctCalc     pgtype.Int4
	KmPerPctCalc           pgtype.Float8
	EstimatedRangeKmCalc   pgtype.Float8
	DaysSpannedCalc        pgtype.Int4
}

// Queries for the telemetry module. sqlc generates package `telemetrydb` from
// these against the schema in migrations/. No other module may import telemetrydb
// (module-scoped DB access — ai/architecture.md §2, ai/go-conventions.md
// §persistence). All writes are append-only inserts (no UPDATE/DELETE): the two
// tables are immutable history.
// Upsert one snapshot: inserts a new row, or REPLACES the existing row for
// the same (account_id, tesla_id, captured_date) if one already exists — the
// newest capture for a calendar day always wins (design D1 of
// telemetry-dedupe-daily-snapshots, which SUPERSEDES the table's prior
// append-only invariant — migration 20260710000002 design D1 of
// RM1-telemetry-add-nightly-snapshots). captured_date is Go-computed
// (snapshotFrom/dateOnly, service.go) from captured_at in the poller's
// configured timezone (design D2) — never a DB expression, because a UNIQUE
// index cannot depend on the runtime POLLER_TIMEZONE env var.
// Distance/range columns store DISPLAY units (km), converted exactly once at
// capture time by calling the tesla adapter's Km() companions — never derived
// on read (telemetry-store-display-units design D1/D3, RM7 Decision 1).
// sentry_mode is bound as a nullable boolean (nil = vehicle did not report
// sentry) so absent stays distinct from a reported off.
// Source A (RM2-telemetry-add-charging-stats): the 5 charge-enrichment columns are
// always non-NULL for rows written after the 20260716000002 migration — snapshotFrom
// stores the actual DTO value pointer-wrapped (D12: no zero-is-absent heuristic).
// NULL is reserved for pre-migration rows only; see design DSA1/DSA3.
// max_range_charge_counter: nullable int, lifetime count of charges to max-range.
// NULL for rows written before 20260801000001 migration (pre-extraction). A real 0
// is stored as non-NULL via pointer-wrap in snapshotFrom (D12/DSA3 convention).
// tpms_pressure_{fl,fr,rl,rr}_psi: nullable REAL, tire pressure in PSI — converted
// exactly once at capture time from the Fleet API's native bar reading by calling
// the tesla adapter's TpmsPressure*PSI() companions (telemetry-store-display-units
// design D1/D3). NULL for rows written before 20260802000001 migration
// (pre-extraction) or when the vehicle did not report TPMS. A 0.0 PSI is stored
// non-NULL (D12/DSA3 convention). No new index: tpms columns ride along on the
// existing heap row fetch.
// latitude/longitude/fast_charger_type dropped in 20260801000001 — lossless in raw_data.
// updated_at is NOT sent as a param: DEFAULT now() handles a fresh INSERT;
// the ON CONFLICT clause explicitly refreshes it to now() on a same-day
// replace (design D5), mirroring UpsertSuperchargerSession's own
// `updated_at = now()`.
// distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
// estimated_range_km_calc, days_spanned_calc: five nullable derived-consumption
// columns computed in Go by deriveConsumption (service.go) BEFORE this query
// runs and bound as ordinary params, exactly like every other typed column
// (telemetry-add-derived-consumption-columns design D3/D6/D8). NULL means "no
// predecessor exists" (D8) or, for the two efficiency columns only, a
// zero/negative battery-used divisor (D2). They are included in the ON
// CONFLICT DO UPDATE SET below so a same-day re-capture recomputes and
// refreshes them identically to every other column — this is the fix for the
// same-day-recapture staleness bug (design D6).
func (q *Queries) InsertVehicleSnapshot(ctx context.Context, arg InsertVehicleSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertVehicleSnapshot,
		arg.AccountID,
		arg.TeslaID,
		arg.CapturedAt,
		arg.RawData,
		arg.BatteryLevelPct,
		arg.BatteryRangeKm,
		arg.ChargingState,
		arg.ChargeLimitSocPct,
		arg.OdometerKm,
		arg.InsideTempC,
		arg.OutsideTempC,
		arg.Locked,
		arg.SentryMode,
		arg.CarVersion,
		arg.ChargeEnergyAddedKwh,
		arg.ChargerPowerKw,
		arg.ChargerVoltageV,
		arg.ChargerActualCurrentA,
		arg.UsableBatteryLevelPct,
		arg.MaxRangeChargeCounter,
		arg.TpmsPressureFlPsi,
		arg.TpmsPressureFrPsi,
		arg.TpmsPressureRlPsi,
		arg.TpmsPressureRrPsi,
		arg.CapturedDate,
		arg.DistanceTraveledKmCalc,
		arg.BatteryUsedPctCalc,
		arg.KmPerPctCalc,
		arg.EstimatedRangeKmCalc,
		arg.DaysSpannedCalc,
	)
	return err
}

const latestSnapshotsByAccount = `-- name: LatestSnapshotsByAccount :many
SELECT DISTINCT ON (tesla_id)
    id, account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date, updated_at,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
FROM vehicle_snapshots
WHERE account_id = $1
ORDER BY tesla_id, captured_at DESC
`

// Return the latest stored snapshot for each vehicle owned by the given account.
// DISTINCT ON (tesla_id) with ORDER BY tesla_id, captured_at DESC picks the row
// with the highest captured_at per tesla_id — one Postgres index scan, no N+1.
// The existing (account_id, tesla_id, captured_at) index covers this query: the
// planner satisfies the WHERE and ORDER BY in a single efficient range scan.
// This is the batch read for the dashboard (tier 5, gateway-read-stored-vehicles);
// it avoids the N+1 that would result from calling ListSnapshotsByVehicle per vehicle.
func (q *Queries) LatestSnapshotsByAccount(ctx context.Context, accountID uuid.UUID) ([]VehicleSnapshot, error) {
	rows, err := q.db.Query(ctx, latestSnapshotsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleSnapshot
	for rows.Next() {
		var i VehicleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.CapturedAt,
			&i.RawData,
			&i.BatteryLevelPct,
			&i.BatteryRangeKm,
			&i.ChargingState,
			&i.ChargeLimitSocPct,
			&i.OdometerKm,
			&i.InsideTempC,
			&i.OutsideTempC,
			&i.Locked,
			&i.SentryMode,
			&i.CarVersion,
			&i.ChargeEnergyAddedKwh,
			&i.ChargerPowerKw,
			&i.ChargerVoltageV,
			&i.ChargerActualCurrentA,
			&i.UsableBatteryLevelPct,
			&i.MaxRangeChargeCounter,
			&i.TpmsPressureFlPsi,
			&i.TpmsPressureFrPsi,
			&i.TpmsPressureRlPsi,
			&i.TpmsPressureRrPsi,
			&i.CapturedDate,
			&i.UpdatedAt,
			&i.DistanceTraveledKmCalc,
			&i.BatteryUsedPctCalc,
			&i.KmPerPctCalc,
			&i.EstimatedRangeKmCalc,
			&i.DaysSpannedCalc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollAttemptsByVehicle = `-- name: ListPollAttemptsByVehicle :many
SELECT id, account_id, tesla_id, attempted_at, outcome, reason FROM poll_attempts
WHERE account_id = $1 AND tesla_id = $2
ORDER BY attempted_at DESC
`

type ListPollAttemptsByVehicleParams struct {
	AccountID uuid.UUID
	TeslaID   int64
}

// Read helper for the DATABASE_URL-gated store tests: every attempt for one
// vehicle, newest first. Not consumed by another module (module-scoped).
func (q *Queries) ListPollAttemptsByVehicle(ctx context.Context, arg ListPollAttemptsByVehicleParams) ([]PollAttempt, error) {
	rows, err := q.db.Query(ctx, listPollAttemptsByVehicle, arg.AccountID, arg.TeslaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollAttempt
	for rows.Next() {
		var i PollAttempt
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.AttemptedAt,
			&i.Outcome,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByVehicle = `-- name: ListSnapshotsByVehicle :many
SELECT
    id, account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date, updated_at,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
FROM vehicle_snapshots
WHERE account_id = $1 AND tesla_id = $2
ORDER BY captured_at DESC
`

type ListSnapshotsByVehicleParams struct {
	AccountID uuid.UUID
	TeslaID   int64
}

// Read helper for the DATABASE_URL-gated store tests: every snapshot for one
// vehicle, newest first. Not consumed by another module (module-scoped).
// Explicit column list (no SELECT *) so sqlc generates a stable struct even when
// schema evolves; latitude/longitude/fast_charger_type removed in 20260801000001.
func (q *Queries) ListSnapshotsByVehicle(ctx context.Context, arg ListSnapshotsByVehicleParams) ([]VehicleSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByVehicle, arg.AccountID, arg.TeslaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleSnapshot
	for rows.Next() {
		var i VehicleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.CapturedAt,
			&i.RawData,
			&i.BatteryLevelPct,
			&i.BatteryRangeKm,
			&i.ChargingState,
			&i.ChargeLimitSocPct,
			&i.OdometerKm,
			&i.InsideTempC,
			&i.OutsideTempC,
			&i.Locked,
			&i.SentryMode,
			&i.CarVersion,
			&i.ChargeEnergyAddedKwh,
			&i.ChargerPowerKw,
			&i.ChargerVoltageV,
			&i.ChargerActualCurrentA,
			&i.UsableBatteryLevelPct,
			&i.MaxRangeChargeCounter,
			&i.TpmsPressureFlPsi,
			&i.TpmsPressureFrPsi,
			&i.TpmsPressureRlPsi,
			&i.TpmsPressureRrPsi,
			&i.CapturedDate,
			&i.UpdatedAt,
			&i.DistanceTraveledKmCalc,
			&i.BatteryUsedPctCalc,
			&i.KmPerPctCalc,
			&i.EstimatedRangeKmCalc,
			&i.DaysSpannedCalc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previousSnapshotForVehicle = `-- name: PreviousSnapshotForVehicle :one
SELECT
    id, account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date, updated_at,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
FROM vehicle_snapshots
WHERE account_id = $1
  AND tesla_id   = $2
  AND captured_at < $3
ORDER BY captured_at DESC
LIMIT 1
`

type PreviousSnapshotForVehicleParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	Before    pgtype.Timestamptz
}

// Return the single most recent snapshot for a vehicle strictly before the
// given instant, or pgx.ErrNoRows when none exists (the vehicle's
// first-ever snapshot — design D8/D10 of telemetry-add-derived-consumption-columns).
// Callers pass dayStart(capturedAt, loc) as `before` (design D7) — the LOCAL
// calendar-day start, not the incoming snapshot's own captured_at — so a
// same-day re-capture cannot select today's own (about-to-be-replaced) row
// as its own predecessor.
// Backward scan of the existing idx_vehicle_snapshots_vehicle_time
// (account_id, tesla_id, captured_at) index (design D7): the planner seeks
// to (account_id, tesla_id, before) and walks the ascending B-tree in
// reverse to satisfy ORDER BY captured_at DESC, stopping after the first
// matching row via LIMIT 1 — no new index.
func (q *Queries) PreviousSnapshotForVehicle(ctx context.Context, arg PreviousSnapshotForVehicleParams) (VehicleSnapshot, error) {
	row := q.db.QueryRow(ctx, previousSnapshotForVehicle, arg.AccountID, arg.TeslaID, arg.Before)
	var i VehicleSnapshot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TeslaID,
		&i.CapturedAt,
		&i.RawData,
		&i.BatteryLevelPct,
		&i.BatteryRangeKm,
		&i.ChargingState,
		&i.ChargeLimitSocPct,
		&i.OdometerKm,
		&i.InsideTempC,
		&i.OutsideTempC,
		&i.Locked,
		&i.SentryMode,
		&i.CarVersion,
		&i.ChargeEnergyAddedKwh,
		&i.ChargerPowerKw,
		&i.ChargerVoltageV,
		&i.ChargerActualCurrentA,
		&i.UsableBatteryLevelPct,
		&i.MaxRangeChargeCounter,
		&i.TpmsPressureFlPsi,
		&i.TpmsPressureFrPsi,
		&i.TpmsPressureRlPsi,
		&i.TpmsPressureRrPsi,
		&i.CapturedDate,
		&i.UpdatedAt,
		&i.DistanceTraveledKmCalc,
		&i.BatteryUsedPctCalc,
		&i.KmPerPctCalc,
		&i.EstimatedRangeKmCalc,
		&i.DaysSpannedCalc,
	)
	return i, err
}

const snapshotsByVehicleBetween = `-- name: SnapshotsByVehicleBetween :many
SELECT
    id, account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date, updated_at,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
FROM vehicle_snapshots
WHERE account_id = $1
  AND tesla_id   = $2
  AND captured_at >= $3
  AND captured_at <  $4
ORDER BY captured_at ASC
LIMIT 400
`

type SnapshotsByVehicleBetweenParams struct {
	AccountID  uuid.UUID
	TeslaID    int64
	StartBound pgtype.Timestamptz
	EndBound   pgtype.Timestamptz
}

// Return the snapshots for a single vehicle (within the given account) whose
// **EffectiveDate calendar day** falls in the caller-supplied `[start, end]` window
// inclusive, ordered oldest-first (ascending by captured_at == ascending by
// EffectiveDate, since EffectiveDate is monotonic in CapturedAt). Used by
// telemetry.Reader.SnapshotsByVehicleBetween to power the bounded history charts
// (RM8 tier 1, MAG-7 date filters). `start` and `end` are whole UTC-midnight-bounded
// calendar days; `end` is inclusive.
//
// Bounds derivation (design D1/D5): EffectiveDate = CapturedAt.AddDate(0,0,-1), i.e.
// EffectiveDate's UTC calendar day == CapturedAt's UTC calendar day minus 1. So
// `EffectiveDate ∈ [start, end]` inclusive ⟺ `CapturedAt ∈ [start+1 day, end+1 day]`
// (calendar days, inclusive both ends). Expressed as TIMESTAMPTZ predicates this is
// the half-open range `[start_bound, end_bound)`:
//
//	start_bound = start + 1 calendar day   (start.AddDate(0,0,1)  — UTC midnight beginning the first eligible capture day)
//	end_bound   = end   + 2 calendar days  (end  .AddDate(0,0,2)  — UTC midnight ending the last eligible capture day, exclusive)
//
// The half-open upper bound makes `end` inclusive without an off-by-one on a
// UTC-midnight `end` instant (design D3).
// The translation `(start, end) → (start_bound, end_bound)` lives INSIDE the dbStore
// implementation (service.go), NOT in the public Reader method (design D5): the
// reader/store seam passes the caller's raw `(start, end)` through unchanged, and the
// dbStore computes and binds the two bounds as pgtype.Timestamptz here.
//
// Why captured_at (TIMESTAMPTZ) and NOT captured_date (DATE) (design D1): captured_at
// is the UTC capture instant EffectiveDate is derived from (rowToSnapshot:
// CapturedAt.Time.AddDate(0,0,-1)), so the query and the mapper are consistent by
// construction with zero timezone coupling. captured_date is Go-computed in the
// poller's configured timezone (POLLER_TIMEZONE, currently America/Bogota, UTC−5) and
// used solely for the (account_id, tesla_id, captured_date) dedupe UNIQUE constraint
// (telemetry-dedupe-daily-snapshots design D2). Filtering on captured_date would
// couple this port's correctness to the poller's timezone and break quietly the moment
// a capture straddles UTC midnight or POLLER_TIMEZONE changes — the exact fragility
// the dedupe change's D2 rejected. (The implicit (account_id, tesla_id, captured_date)
// unique index would *serve* such a query, but semantic correctness disqualifies it.)
//
// Index reuse (D2): the existing idx_vehicle_snapshots_vehicle_time
// (account_id, tesla_id, captured_at) is an ASCENDING index. The query's
// (account_id = $1 AND tesla_id = $2 AND captured_at >= $3 AND captured_at < $4
// ORDER BY captured_at ASC) is a forward range scan: the planner seeks to
// (account_id, tesla_id, start_bound) and reads forward in index order, satisfying
// both WHERE and ORDER BY with no sort step; the upper bound `captured_at < end_bound`
// prunes the scan in-place. This is the identical access pattern SnapshotsByVehicleSince
// uses, with one extra range predicate — strictly cheaper than the open Since scan for
// the same dashboard window. No new index, no migration, no new column (design D2 —
// the `database` design-gate is NOT triggered).
//
// LIMIT 400 (D3, parity with SnapshotsByVehicleSince's D4): safety cap against an
// accidentally large result set if capture cadence ever increases. The HTTP contract
// (Decision #2) caps the window at <= 90 days; the gateway's 1-day lookback (Decision
// #4) adds one day, so the realistic max return is ~91 rows (one nightly snapshot per
// calendar day under the current cadence). 400 comfortably exceeds that without being
// so large it re-introduces the unbounded-scan risk the cap exists to prevent; the
// bounded window itself (not the LIMIT) is the real protection on this path.
func (q *Queries) SnapshotsByVehicleBetween(ctx context.Context, arg SnapshotsByVehicleBetweenParams) ([]VehicleSnapshot, error) {
	rows, err := q.db.Query(ctx, snapshotsByVehicleBetween,
		arg.AccountID,
		arg.TeslaID,
		arg.StartBound,
		arg.EndBound,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleSnapshot
	for rows.Next() {
		var i VehicleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.CapturedAt,
			&i.RawData,
			&i.BatteryLevelPct,
			&i.BatteryRangeKm,
			&i.ChargingState,
			&i.ChargeLimitSocPct,
			&i.OdometerKm,
			&i.InsideTempC,
			&i.OutsideTempC,
			&i.Locked,
			&i.SentryMode,
			&i.CarVersion,
			&i.ChargeEnergyAddedKwh,
			&i.ChargerPowerKw,
			&i.ChargerVoltageV,
			&i.ChargerActualCurrentA,
			&i.UsableBatteryLevelPct,
			&i.MaxRangeChargeCounter,
			&i.TpmsPressureFlPsi,
			&i.TpmsPressureFrPsi,
			&i.TpmsPressureRlPsi,
			&i.TpmsPressureRrPsi,
			&i.CapturedDate,
			&i.UpdatedAt,
			&i.DistanceTraveledKmCalc,
			&i.BatteryUsedPctCalc,
			&i.KmPerPctCalc,
			&i.EstimatedRangeKmCalc,
			&i.DaysSpannedCalc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotsByVehicleSince = `-- name: SnapshotsByVehicleSince :many
SELECT
    id, account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date, updated_at,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
FROM vehicle_snapshots
WHERE account_id = $1
  AND tesla_id   = $2
  AND captured_at >= $3
ORDER BY captured_at ASC
LIMIT 400
`

type SnapshotsByVehicleSinceParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	Since     pgtype.Timestamptz
}

// Return all snapshots for a single vehicle (within the given account) captured at or
// after `since`, ordered oldest-first. Used by telemetry.Reader.SnapshotsByVehicleSince
// to power the odometer/battery history charts (RM5 tier 1).
//
// Index reuse (D3): the existing idx_vehicle_snapshots_vehicle_time
// (account_id, tesla_id, captured_at) is an ASCENDING index. The query's
// (account_id = $1 AND tesla_id = $2 AND captured_at >= $3 ORDER BY captured_at ASC)
// is a forward range scan: the planner seeks to (account_id, tesla_id, since) and
// reads forward in index order, satisfying both WHERE and ORDER BY with no sort step.
//
// LIMIT 400 (D4): safety cap against an accidentally large result set if capture
// cadence ever increases. A 30-day window returns ~30 rows under the current nightly
// schedule — 400 comfortably exceeds any realistic dashboard window (~13 months).
func (q *Queries) SnapshotsByVehicleSince(ctx context.Context, arg SnapshotsByVehicleSinceParams) ([]VehicleSnapshot, error) {
	rows, err := q.db.Query(ctx, snapshotsByVehicleSince, arg.AccountID, arg.TeslaID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleSnapshot
	for rows.Next() {
		var i VehicleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.CapturedAt,
			&i.RawData,
			&i.BatteryLevelPct,
			&i.BatteryRangeKm,
			&i.ChargingState,
			&i.ChargeLimitSocPct,
			&i.OdometerKm,
			&i.InsideTempC,
			&i.OutsideTempC,
			&i.Locked,
			&i.SentryMode,
			&i.CarVersion,
			&i.ChargeEnergyAddedKwh,
			&i.ChargerPowerKw,
			&i.ChargerVoltageV,
			&i.ChargerActualCurrentA,
			&i.UsableBatteryLevelPct,
			&i.MaxRangeChargeCounter,
			&i.TpmsPressureFlPsi,
			&i.TpmsPressureFrPsi,
			&i.TpmsPressureRlPsi,
			&i.TpmsPressureRrPsi,
			&i.CapturedDate,
			&i.UpdatedAt,
			&i.DistanceTraveledKmCalc,
			&i.BatteryUsedPctCalc,
			&i.KmPerPctCalc,
			&i.EstimatedRangeKmCalc,
			&i.DaysSpannedCalc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotsByVehicleUpdatedSince = `-- name: SnapshotsByVehicleUpdatedSince :many
SELECT
    id, account_id, tesla_id, captured_at, raw_data,
    battery_level_pct, battery_range_km, charging_state, charge_limit_soc_pct,
    odometer_km, inside_temp_c, outside_temp_c, locked, sentry_mode,
    car_version,
    charge_energy_added_kwh, charger_power_kw, charger_voltage_v,
    charger_actual_current_a, usable_battery_level_pct,
    max_range_charge_counter,
    tpms_pressure_fl_psi, tpms_pressure_fr_psi, tpms_pressure_rl_psi, tpms_pressure_rr_psi,
    captured_date, updated_at,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc
FROM vehicle_snapshots
WHERE account_id = $1
  AND tesla_id   = $2
  AND updated_at >= $3
ORDER BY updated_at ASC
`

type SnapshotsByVehicleUpdatedSinceParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	Since     pgtype.Timestamptz
}

// Return every snapshot for a single vehicle (within the given account) whose
// updated_at is at or after `since`, ordered oldest-first by updated_at. Used by
// telemetry.Reader.SnapshotsByVehicleUpdatedSince to let internal/analytics'
// Recalculator (RM29-analytics-add-vehicle-metrics) detect which snapshots
// changed recently -- including a same-day REPLACE via the existing UPSERT
// (design D1 of telemetry-dedupe-daily-snapshots), which advances updated_at
// without necessarily changing captured_at's calendar day.
//
// Index reuse: the existing idx_vehicle_snapshots_vehicle_time
// (account_id, tesla_id, captured_at) is NOT sorted on updated_at, so this
// query cannot use it as a pure ORDER BY-satisfying range scan the way
// SnapshotsByVehicleSince does on captured_at. It STILL prunes the scan to
// this one vehicle's rows via the index's (account_id, tesla_id) leading-
// column prefix before the updated_at predicate and sort are applied --
// updated_at is a residual filter within that scan, per this change's
// explicit design call (no new index; verified via EXPLAIN in the
// DB-integration test, RM29-analytics-add-vehicle-metrics Wave 6).
func (q *Queries) SnapshotsByVehicleUpdatedSince(ctx context.Context, arg SnapshotsByVehicleUpdatedSinceParams) ([]VehicleSnapshot, error) {
	rows, err := q.db.Query(ctx, snapshotsByVehicleUpdatedSince, arg.AccountID, arg.TeslaID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleSnapshot
	for rows.Next() {
		var i VehicleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TeslaID,
			&i.CapturedAt,
			&i.RawData,
			&i.BatteryLevelPct,
			&i.BatteryRangeKm,
			&i.ChargingState,
			&i.ChargeLimitSocPct,
			&i.OdometerKm,
			&i.InsideTempC,
			&i.OutsideTempC,
			&i.Locked,
			&i.SentryMode,
			&i.CarVersion,
			&i.ChargeEnergyAddedKwh,
			&i.ChargerPowerKw,
			&i.ChargerVoltageV,
			&i.ChargerActualCurrentA,
			&i.UsableBatteryLevelPct,
			&i.MaxRangeChargeCounter,
			&i.TpmsPressureFlPsi,
			&i.TpmsPressureFrPsi,
			&i.TpmsPressureRlPsi,
			&i.TpmsPressureRrPsi,
			&i.CapturedDate,
			&i.UpdatedAt,
			&i.DistanceTraveledKmCalc,
			&i.BatteryUsedPctCalc,
			&i.KmPerPctCalc,
			&i.EstimatedRangeKmCalc,
			&i.DaysSpannedCalc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const superchargerSessionsByAccount = `-- name: SuperchargerSessionsByAccount :many
SELECT id, session_id, account_id, vin, tesla_id, site_location_name, country_code, charge_start_date_time, charge_stop_date_time, unlatch_date_time, billing_type, vehicle_make_type, energy_kwh, total_cost, currency, is_paid, raw_data, created_at, updated_at, start_battery_pct, end_battery_pct, battery_pct_source, start_battery_pct_est, end_battery_pct_est FROM supercharger_sessions
WHERE account_id = $1
ORDER BY charge_start_date_time DESC
LIMIT $2
`

type SuperchargerSessionsByAccountParams struct {
	AccountID  uuid.UUID
	LimitCount int32
}

// Return all Supercharger sessions for the given account, newest first, up to
// limit_count rows. Uses idx_supercharger_sessions_account_time
// (account_id, charge_start_date_time DESC) — the account_id prefix prunes to
// the tenant; DESC order matches the ORDER BY so no sort step is needed.
// Design DBS4 / DBS6: account-wide spend/energy dashboard access pattern.
func (q *Queries) SuperchargerSessionsByAccount(ctx context.Context, arg SuperchargerSessionsByAccountParams) ([]SuperchargerSession, error) {
	rows, err := q.db.Query(ctx, superchargerSessionsByAccount, arg.AccountID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuperchargerSession
	for rows.Next() {
		var i SuperchargerSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AccountID,
			&i.Vin,
			&i.TeslaID,
			&i.SiteLocationName,
			&i.CountryCode,
			&i.ChargeStartDateTime,
			&i.ChargeStopDateTime,
			&i.UnlatchDateTime,
			&i.BillingType,
			&i.VehicleMakeType,
			&i.EnergyKwh,
			&i.TotalCost,
			&i.Currency,
			&i.IsPaid,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.BatteryPctSource,
			&i.StartBatteryPctEst,
			&i.EndBatteryPctEst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const superchargerSessionsByVehicle = `-- name: SuperchargerSessionsByVehicle :many
SELECT id, session_id, account_id, vin, tesla_id, site_location_name, country_code, charge_start_date_time, charge_stop_date_time, unlatch_date_time, billing_type, vehicle_make_type, energy_kwh, total_cost, currency, is_paid, raw_data, created_at, updated_at, start_battery_pct, end_battery_pct, battery_pct_source, start_battery_pct_est, end_battery_pct_est FROM supercharger_sessions
WHERE account_id = $1
  AND tesla_id = $2
ORDER BY charge_start_date_time DESC
LIMIT $3
`

type SuperchargerSessionsByVehicleParams struct {
	AccountID  uuid.UUID
	TeslaID    pgtype.Int8
	LimitCount int32
}

// Return Supercharger sessions for one vehicle within an account, newest first,
// up to limit_count rows. Uses idx_supercharger_sessions_vehicle_time
// (account_id, tesla_id, charge_start_date_time DESC) — both WHERE columns are
// the leading index columns so the planner satisfies the filter and the ORDER BY
// in a single range scan without a sort step.
// Design DBS4 / DBS6: per-vehicle charging history dashboard access pattern.
func (q *Queries) SuperchargerSessionsByVehicle(ctx context.Context, arg SuperchargerSessionsByVehicleParams) ([]SuperchargerSession, error) {
	rows, err := q.db.Query(ctx, superchargerSessionsByVehicle, arg.AccountID, arg.TeslaID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuperchargerSession
	for rows.Next() {
		var i SuperchargerSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AccountID,
			&i.Vin,
			&i.TeslaID,
			&i.SiteLocationName,
			&i.CountryCode,
			&i.ChargeStartDateTime,
			&i.ChargeStopDateTime,
			&i.UnlatchDateTime,
			&i.BillingType,
			&i.VehicleMakeType,
			&i.EnergyKwh,
			&i.TotalCost,
			&i.Currency,
			&i.IsPaid,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.BatteryPctSource,
			&i.StartBatteryPctEst,
			&i.EndBatteryPctEst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const superchargerSessionsByVehicleBetween = `-- name: SuperchargerSessionsByVehicleBetween :many
SELECT id, session_id, account_id, vin, tesla_id, site_location_name, country_code, charge_start_date_time, charge_stop_date_time, unlatch_date_time, billing_type, vehicle_make_type, energy_kwh, total_cost, currency, is_paid, raw_data, created_at, updated_at, start_battery_pct, end_battery_pct, battery_pct_source, start_battery_pct_est, end_battery_pct_est FROM supercharger_sessions
WHERE account_id = $1
  AND tesla_id   = $2
  AND charge_stop_date_time >= $3
  AND charge_stop_date_time <  $4
ORDER BY charge_stop_date_time ASC
`

type SuperchargerSessionsByVehicleBetweenParams struct {
	AccountID uuid.UUID
	TeslaID   pgtype.Int8
	Start     pgtype.Timestamptz
	EndBound  pgtype.Timestamptz
}

// Return Supercharger sessions for one vehicle within an account whose
// charge_stop_date_time falls in the caller-supplied [start, end] window,
// inclusive of the whole end calendar day, ordered oldest-first (ascending
// by charge_stop_date_time). Used by
// SuperchargerReader.SuperchargerSessionsByVehicleBetween to power RM28's
// battery-consumed-per-day derivation (roadmap D9/D12).
//
// Filters on charge_stop_date_time, NOT charge_start_date_time (D12): energy
// is fully delivered at session stop, which is what end_battery_pct
// corresponds to, so a session belongs to the day its STOP falls in even
// when it started the day before (a session spanning midnight IS included in
// the window containing its stop instant -- deliberate, per D12).
//
// Bounds (start, end are whole UTC-midnight-bounded calendar days; end
// inclusive, matching this project's platform-wide HTTP date-filter
// convention, ai/go-conventions.md §"Read optimization"): end_bound = end +
// 1 calendar day (computed in Go, reader.go's
// SuperchargerSessionsByVehicleBetween, mirroring
// Reader.SnapshotsByVehicleBetween's own bounds-translation precedent of
// doing the day-arithmetic in Go, not in SQL) so
// WHERE charge_stop_date_time >= start AND charge_stop_date_time < end_bound
// includes every instant of the end calendar day without an off-by-one on a
// UTC-midnight end value. Simpler than SnapshotsByVehicleBetween's two-sided
// +1/+2-day shift: that method filters on captured_at to select rows by
// their DERIVED EffectiveDate (one calendar day earlier than the row's own
// timestamp); this method filters directly on charge_stop_date_time, which
// already IS the value being windowed -- no EffectiveDate-style lag to
// compensate for, so only the upper bound needs translating.
//
// Index reuse: idx_supercharger_sessions_vehicle_time
// (account_id, tesla_id, charge_start_date_time DESC) does NOT fully serve
// this query -- it is sorted on charge_start_date_time, not
// charge_stop_date_time, so the stop-time predicate cannot be satisfied as a
// pure index range scan. It STILL prunes the scan to this one vehicle's rows
// via its (account_id, tesla_id) leading-column prefix before the
// stop-time filter is applied in-memory -- see design.md's Index Plan for
// why no third, dedicated (account_id, tesla_id, charge_stop_date_time)
// index is added in this change, and the documented fallback if per-vehicle
// session volume ever grows enough to make that decision wrong.
//
// No LIMIT: this is a bounded date-range query, not an unbounded "most
// recent N" query -- the caller-supplied window is the safety bound, exactly
// like Reader.SnapshotsByVehicleBetween's own reasoning (that method DOES
// still add a defensive LIMIT 400 on top of its window, design D3 there; this
// query does not add an equivalent cap -- see design.md's Index Plan for why
// that asymmetry is deliberate, not an oversight).
func (q *Queries) SuperchargerSessionsByVehicleBetween(ctx context.Context, arg SuperchargerSessionsByVehicleBetweenParams) ([]SuperchargerSession, error) {
	rows, err := q.db.Query(ctx, superchargerSessionsByVehicleBetween,
		arg.AccountID,
		arg.TeslaID,
		arg.Start,
		arg.EndBound,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuperchargerSession
	for rows.Next() {
		var i SuperchargerSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AccountID,
			&i.Vin,
			&i.TeslaID,
			&i.SiteLocationName,
			&i.CountryCode,
			&i.ChargeStartDateTime,
			&i.ChargeStopDateTime,
			&i.UnlatchDateTime,
			&i.BillingType,
			&i.VehicleMakeType,
			&i.EnergyKwh,
			&i.TotalCost,
			&i.Currency,
			&i.IsPaid,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.BatteryPctSource,
			&i.StartBatteryPctEst,
			&i.EndBatteryPctEst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const superchargerSessionsByVehicleUpdatedSince = `-- name: SuperchargerSessionsByVehicleUpdatedSince :many
SELECT id, session_id, account_id, vin, tesla_id, site_location_name, country_code, charge_start_date_time, charge_stop_date_time, unlatch_date_time, billing_type, vehicle_make_type, energy_kwh, total_cost, currency, is_paid, raw_data, created_at, updated_at, start_battery_pct, end_battery_pct, battery_pct_source, start_battery_pct_est, end_battery_pct_est FROM supercharger_sessions
WHERE account_id = $1
  AND tesla_id   = $2
  AND updated_at >= $3
ORDER BY updated_at ASC
`

type SuperchargerSessionsByVehicleUpdatedSinceParams struct {
	AccountID uuid.UUID
	TeslaID   pgtype.Int8
	Since     pgtype.Timestamptz
}

// Return every Supercharger session for one vehicle within an account whose
// updated_at is at or after `since`, ordered oldest-first by updated_at. Used by
// SuperchargerReader.SuperchargerSessionsByVehicleUpdatedSince to let
// internal/analytics' Recalculator (RM29-analytics-add-vehicle-metrics) detect
// which sessions changed recently -- including a billing-state revision on a
// session weeks old (design DBS3: supercharger_sessions is not append-only;
// is_paid / invoice status mutates post-session), whose charge_start_date_time /
// charge_stop_date_time stay unchanged while updated_at refreshes.
//
// Index reuse: idx_supercharger_sessions_vehicle_time
// (account_id, tesla_id, charge_start_date_time DESC) is not sorted on
// updated_at, so this query cannot use it as a pure ORDER BY-satisfying range
// scan. It STILL prunes the scan to this one vehicle's rows via its
// (account_id, tesla_id) leading-column prefix before the updated_at predicate
// and sort are applied -- updated_at is a residual filter within that scan, per
// this change's explicit design call (no new index; verified via EXPLAIN in the
// DB-integration test, RM29-analytics-add-vehicle-metrics Wave 6).
func (q *Queries) SuperchargerSessionsByVehicleUpdatedSince(ctx context.Context, arg SuperchargerSessionsByVehicleUpdatedSinceParams) ([]SuperchargerSession, error) {
	rows, err := q.db.Query(ctx, superchargerSessionsByVehicleUpdatedSince, arg.AccountID, arg.TeslaID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuperchargerSession
	for rows.Next() {
		var i SuperchargerSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AccountID,
			&i.Vin,
			&i.TeslaID,
			&i.SiteLocationName,
			&i.CountryCode,
			&i.ChargeStartDateTime,
			&i.ChargeStopDateTime,
			&i.UnlatchDateTime,
			&i.BillingType,
			&i.VehicleMakeType,
			&i.EnergyKwh,
			&i.TotalCost,
			&i.Currency,
			&i.IsPaid,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartBatteryPct,
			&i.EndBatteryPct,
			&i.BatteryPctSource,
			&i.StartBatteryPctEst,
			&i.EndBatteryPctEst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChargeGap = `-- name: UpsertChargeGap :exec
INSERT INTO charge_gaps (
    account_id, tesla_id, vin, gap_date, missing_charging_type
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (account_id, tesla_id, gap_date) DO UPDATE SET
    vin                    = EXCLUDED.vin,
    missing_charging_type  = EXCLUDED.missing_charging_type,
    updated_at             = now()
`

type UpsertChargeGapParams struct {
	AccountID           uuid.UUID
	TeslaID             int64
	Vin                 string
	GapDate             pgtype.Date
	MissingChargingType string
}

// Upsert one flagged vehicle-day. On conflict with the
// charge_gaps_account_tesla_date_unique constraint, refresh vin (in case the
// vehicle's VIN changed since the day was first flagged -- cheap safety, not
// an expected case) and missing_charging_type (the inferred type can change
// between nightly runs if detection logic evolves, or if a Supercharger
// session with NULL percentages later appears for a day previously inferred
// MANUAL), and refresh updated_at to now(). created_at is DELIBERATELY
// ABSENT from the SET clause -- design D-Table2/the table's own column
// comment: it must record when this vehicle-day was FIRST flagged, not the
// most recent confirmation.
func (q *Queries) UpsertChargeGap(ctx context.Context, arg UpsertChargeGapParams) error {
	_, err := q.db.Exec(ctx, upsertChargeGap,
		arg.AccountID,
		arg.TeslaID,
		arg.Vin,
		arg.GapDate,
		arg.MissingChargingType,
	)
	return err
}

const upsertSuperchargerSession = `-- name: UpsertSuperchargerSession :exec
INSERT INTO supercharger_sessions (
    session_id, account_id, vin, tesla_id,
    site_location_name, country_code,
    charge_start_date_time, charge_stop_date_time, unlatch_date_time,
    billing_type, vehicle_make_type,
    energy_kwh, total_cost, currency, is_paid,
    raw_data
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13, $14, $15,
    $16
)
ON CONFLICT (session_id) DO UPDATE SET
    raw_data   = EXCLUDED.raw_data,
    energy_kwh = EXCLUDED.energy_kwh,
    total_cost = EXCLUDED.total_cost,
    currency   = EXCLUDED.currency,
    is_paid    = EXCLUDED.is_paid,
    tesla_id   = EXCLUDED.tesla_id,
    updated_at = now()
`

type UpsertSuperchargerSessionParams struct {
	SessionID           int64
	AccountID           uuid.UUID
	Vin                 string
	TeslaID             pgtype.Int8
	SiteLocationName    string
	CountryCode         string
	ChargeStartDateTime pgtype.Timestamptz
	ChargeStopDateTime  pgtype.Timestamptz
	UnlatchDateTime     pgtype.Timestamptz
	BillingType         string
	VehicleMakeType     string
	EnergyKwh           pgtype.Float8
	TotalCost           pgtype.Float8
	Currency            pgtype.Text
	IsPaid              pgtype.Bool
	RawData             []byte
}

// LOAD-BEARING (R3, RM27-telemetry-add-supercharger-battery-pct): start_battery_pct,
// end_battery_pct, battery_pct_source, start_battery_pct_est, and end_battery_pct_est
// are DELIBERATELY ABSENT from both the INSERT column list and the ON CONFLICT DO
// UPDATE SET clause below. The first three are a human-owned verification/override
// channel; the last two are a frozen, write-once verification-time snapshot of the
// estimate (design D6) -- NEVER refreshed, NEVER a cache read by internal/analytics
// (see the column comments added by migration 20260815000001). If this query touched
// any of the five, a user's verified value or its frozen snapshot would be silently
// overwritten by the next nightly re-upsert. A fresh INSERT leaves all five at their
// column default (NULL); a re-upsert never assigns any of them. A future writer for
// these columns belongs on a dedicated query on a dedicated Writer port (out of
// scope here, backlog entry 11) -- do not "complete the pattern" by adding them here.
// Upsert one Supercharger session. On conflict with the session_id UNIQUE constraint,
// refresh only the mutable/derived columns (raw_data, derived fields, tesla_id,
// updated_at). Immutable columns (session_id, account_id, vin, location name,
// country, timestamps, billing fields, created_at) are never overwritten.
// Design DBS3: supercharger_sessions is NOT append-only; billing state mutates
// post-session (is_paid, invoice status change after midnight).
func (q *Queries) UpsertSuperchargerSession(ctx context.Context, arg UpsertSuperchargerSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSuperchargerSession,
		arg.SessionID,
		arg.AccountID,
		arg.Vin,
		arg.TeslaID,
		arg.SiteLocationName,
		arg.CountryCode,
		arg.ChargeStartDateTime,
		arg.ChargeStopDateTime,
		arg.UnlatchDateTime,
		arg.BillingType,
		arg.VehicleMakeType,
		arg.EnergyKwh,
		arg.TotalCost,
		arg.Currency,
		arg.IsPaid,
		arg.RawData,
	)
	return err
}
