-- Stamp the four module baselines as already applied, without running them.
--
-- Run this ONCE per existing database (dev, then prod). It creates each module's
-- version ledger and records version 20260917000001 as applied, so goose skips the
-- baseline on a database that already has every object.
--
-- goose v3.27.3 has no stamp or force command, which is why this is hand-written
-- SQL. The CREATE TABLE below is goose's own Postgres DDL, copied from
-- internal/dialects/postgres.go:19 of the pinned version, so the table this creates
-- and the table goose would have created are identical.
--
-- One transaction: all four ledgers appear together, or none does.
--
-- Safe to run against prod BEFORE the deploy. The running image reads
-- public.goose_db_version and cannot see these tables.
--
-- It is NOT idempotent: a second run fails on "relation already exists" because the
-- tables are already there. That failure is the correct answer — it means this
-- database is already stamped.

BEGIN;

CREATE TABLE account.goose_db_version (
    id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint  NOT NULL,
    is_applied boolean NOT NULL,
    tstamp     timestamp NOT NULL DEFAULT now()
);

-- LIKE ... INCLUDING ALL copies the column list, the identity and the primary key,
-- so the four ledgers cannot drift from each other by a typo.
CREATE TABLE telemetry.goose_db_version (LIKE account.goose_db_version INCLUDING ALL);
CREATE TABLE charging.goose_db_version  (LIKE account.goose_db_version INCLUDING ALL);
CREATE TABLE analytics.goose_db_version (LIKE account.goose_db_version INCLUDING ALL);

-- Two rows each: goose's own version-0 marker, then the baseline.
-- The 0 row is what the goose CLI writes when it creates a ledger itself, so this
-- matches the shape public.goose_db_version already has. Nothing reads it.
INSERT INTO account.goose_db_version   (version_id, is_applied) VALUES (0, true), (20260917000001, true);
INSERT INTO telemetry.goose_db_version (version_id, is_applied) VALUES (0, true), (20260917000001, true);
INSERT INTO charging.goose_db_version  (version_id, is_applied) VALUES (0, true), (20260917000001, true);
INSERT INTO analytics.goose_db_version (version_id, is_applied) VALUES (0, true), (20260917000001, true);

COMMIT;
