-- Adds analytics.vehicle_metrics.tesla_range_100_pct_km_calc -- the range the
-- vehicle would have on a full battery, according to Tesla's OWN reported
-- range -- and renames estimated_range_km_calc to
-- efficiency_range_100_pct_km_calc so the two "range at 100%" figures on this
-- table say, in their names, which source each one comes from.
--
-- The new column is the ONLY derived column on this table that Postgres
-- computes itself. Every other one needs the PREVIOUS day's row, which a
-- generated column cannot see. This one needs only two values already on its
-- own row, so generating it removes the write-path code AND the backfill, and
-- leaves the formula written exactly once.
--
-- RENAME COLUMN is catalog-only (no table rewrite, no data loss).
-- ADD COLUMN ... GENERATED ... STORED DOES rewrite the table and holds an
-- ACCESS EXCLUSIVE lock while it runs -- apply it away from the nightly
-- poller window.

-- +goose Up

ALTER TABLE analytics.vehicle_metrics
    RENAME COLUMN estimated_range_km_calc TO efficiency_range_100_pct_km_calc;

ALTER TABLE analytics.vehicle_metrics
    ADD COLUMN tesla_range_100_pct_km_calc double precision -- delta:allow: a same-row ratio projected to 100%, never a day-over-day delta
        GENERATED ALWAYS AS (battery_range_km / NULLIF(battery_level_pct, 0) * 100) STORED;

-- COMMENT: COLUMN vehicle_metrics.tesla_range_100_pct_km_calc
-- +goose StatementBegin
COMMENT ON COLUMN analytics.vehicle_metrics.tesla_range_100_pct_km_calc IS 'The range this vehicle would have on a FULL battery, projected from Tesla''s own reported range: battery_range_km divided by battery_level_pct, times 100. Generated by POSTGRES, not by Go -- the only column on this table that is. Nothing in internal/analytics writes it, no backfill ever filled it, and the UPSERT must never name it: Postgres recomputes it from this row''s own battery_range_km and battery_level_pct on every insert and every update, so it cannot drift from its formula and cannot be stale. Every other derived column here needs the PREVIOUS day''s row, which a generated column cannot read -- that, and nothing else, is why the rest live in Go. NULL only when battery_level_pct is 0 (the NULLIF divisor guard); unlike the _calc columns around it, it does NOT need a predecessor day and is therefore populated on a vehicle''s very first row. NOT ROUNDED, on purpose: battery_level_pct is an INTEGER, so Tesla''s own 1-point quantization already puts roughly 4 km of noise on a single day''s value, and rounding on write would destroy precision without removing that noise. Average it over a month to see through it -- that is what vehicle_monthly_metrics.tesla_range_100_pct_km_calc is for. Falling month over month is the intended battery-degradation signal, but a single low reading is NOT degradation: cold weather and Tesla''s own range estimator move this number too. Do NOT confuse it with efficiency_range_100_pct_km_calc, which answers the same question from the opposite source -- how the vehicle was actually DRIVEN that day, not what Tesla rates it at.';
-- +goose StatementEnd

-- COMMENT: COLUMN vehicle_metrics.efficiency_range_100_pct_km_calc
-- +goose StatementBegin
COMMENT ON COLUMN analytics.vehicle_metrics.efficiency_range_100_pct_km_calc IS 'The range this vehicle would have on a FULL battery at the efficiency it was ACTUALLY DRIVEN that day: km_per_pct_calc times 100, and nothing else. Computed in Go by internal/analytics deriveConsumption, which is where both this column and km_per_pct_calc are produced. NULL under the identical guard condition as km_per_pct_calc -- no predecessor snapshot, or a consumed_pct divisor that is zero or negative. Named estimated_range_km_calc until this migration. The old name said "estimated" without saying estimated FROM WHAT, and a reader had to open consumption.go to find out; worse, it read like a battery-capacity figure, which it is not. The new name carries its source: it is the driving-EFFICIENCY projection, the sibling of tesla_range_100_pct_km_calc, which projects Tesla''s own rated range instead. The two answer the same question and routinely disagree -- a heavy-footed day drops this one while leaving Tesla''s untouched. "efficiency" is the word the dashboard already shows for km_per_pct_calc (i18n dashboard.efficiency, ES "Eficiencia" / EN "Efficiency"), so this name adds no new vocabulary.';
-- +goose StatementEnd

-- +goose Down

ALTER TABLE analytics.vehicle_metrics
    DROP COLUMN tesla_range_100_pct_km_calc;

ALTER TABLE analytics.vehicle_metrics
    RENAME COLUMN efficiency_range_100_pct_km_calc TO estimated_range_km_calc;
