// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package analyticsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVehicleMetricsInRangeExcept = `-- name: DeleteVehicleMetricsInRangeExcept :exec
DELETE FROM vehicle_metrics
WHERE account_id  = $1
  AND tesla_id    = $2
  AND metric_date BETWEEN $3 AND $4
  AND metric_date != ALL($5::date[])
`

type DeleteVehicleMetricsInRangeExceptParams struct {
	AccountID   uuid.UUID
	TeslaID     int64
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	MetricDates []pgtype.Date
}

// Delete every vehicle_metrics row in [start, end] for this vehicle whose
// metric_date is NOT among the dates Recalculate just produced (design D11).
// Under the dense-table revision, "stale" means "no snapshot exists for that
// day at all anymore" (e.g. a backfill correction removed a
// vehicle_snapshots row) — a narrower, simpler condition than the pre-revision
// sparse design needed, since a computable-or-not row is now produced for
// every day that still has a snapshot.
// An empty metric_dates array (Recalculate produced no rows at all for the
// window, e.g. every snapshot in range was itself removed) correctly deletes
// every existing row in range: `!= ALL('{}')` is true for every row, since
// there are no elements to compare against.
// Served by vehicle_metrics_account_tesla_date_unique's own index (Index Plan,
// read pattern #3) — no separate CREATE INDEX.
func (q *Queries) DeleteVehicleMetricsInRangeExcept(ctx context.Context, arg DeleteVehicleMetricsInRangeExceptParams) error {
	_, err := q.db.Exec(ctx, deleteVehicleMetricsInRangeExcept,
		arg.AccountID,
		arg.TeslaID,
		arg.StartDate,
		arg.EndDate,
		arg.MetricDates,
	)
	return err
}

const getVehicleMetricWatermark = `-- name: GetVehicleMetricWatermark :one
SELECT source_updated_at
FROM vehicle_metric_watermarks
WHERE account_id = $1
  AND tesla_id   = $2
  AND source     = $3
`

type GetVehicleMetricWatermarkParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	Source    string
}

// Single-row cursor lookup for one (account_id, tesla_id, source) — design
// D2/D3. Returns pgx.ErrNoRows when no watermark exists yet for this source,
// which internal/analytics.Recalculator.Reconcile treats as "epoch": the
// source has never been reconciled for this vehicle, so it backfills the
// vehicle's full history in one pass (design D7). Served entirely by
// vehicle_metric_watermarks_account_tesla_source_unique's own index (Index
// Plan, read pattern #4) — no separate CREATE INDEX.
func (q *Queries) GetVehicleMetricWatermark(ctx context.Context, arg GetVehicleMetricWatermarkParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getVehicleMetricWatermark, arg.AccountID, arg.TeslaID, arg.Source)
	var source_updated_at pgtype.Timestamptz
	err := row.Scan(&source_updated_at)
	return source_updated_at, err
}

const upsertVehicleMetric = `-- name: UpsertVehicleMetric :exec

INSERT INTO vehicle_metrics (
    account_id, tesla_id, metric_date,
    battery_level_pct, odometer_km, battery_range_km,
    distance_traveled_km_calc, battery_used_pct_calc, km_per_pct_calc,
    estimated_range_km_calc, days_spanned_calc,
    consumed_pct, flagged, missing_charging_type
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13, $14
)
ON CONFLICT (account_id, tesla_id, metric_date) DO UPDATE SET
    battery_level_pct         = EXCLUDED.battery_level_pct,
    odometer_km                = EXCLUDED.odometer_km,
    battery_range_km           = EXCLUDED.battery_range_km,
    distance_traveled_km_calc  = EXCLUDED.distance_traveled_km_calc,
    battery_used_pct_calc      = EXCLUDED.battery_used_pct_calc,
    km_per_pct_calc             = EXCLUDED.km_per_pct_calc,
    estimated_range_km_calc     = EXCLUDED.estimated_range_km_calc,
    days_spanned_calc           = EXCLUDED.days_spanned_calc,
    consumed_pct               = EXCLUDED.consumed_pct,
    flagged                    = EXCLUDED.flagged,
    missing_charging_type      = EXCLUDED.missing_charging_type,
    updated_at                 = now()
`

type UpsertVehicleMetricParams struct {
	AccountID              uuid.UUID
	TeslaID                int64
	MetricDate             pgtype.Date
	BatteryLevelPct        int32
	OdometerKm             float64
	BatteryRangeKm         float64
	DistanceTraveledKmCalc pgtype.Float8
	BatteryUsedPctCalc     pgtype.Int4
	KmPerPctCalc           pgtype.Float8
	EstimatedRangeKmCalc   pgtype.Float8
	DaysSpannedCalc        pgtype.Int4
	ConsumedPct            pgtype.Float8
	Flagged                bool
	MissingChargingType    pgtype.Text
}

// Queries for the analytics module. sqlc generates package `analyticsdb` from
// these against the schema in migrations/. No other module may import
// analyticsdb (module-scoped DB access — ai/architecture.md §2,
// ai/go-conventions.md §persistence). This is the module's first-ever
// persistence layer (RM29-analytics-add-vehicle-metrics, MAG-26 tier 3);
// both tables are written exclusively by internal/analytics.Recalculator and
// read exclusively by internal/analytics.Reader — see design.md D9–D13 and
// the "Database Changes" section for the full schema rationale.
// Upsert one vehicle_metrics row (design D11). On conflict with
// vehicle_metrics_account_tesla_date_unique, refresh every column
// Recalculate/deriveVehicleMetrics computed for this day, including the
// nullable _calc columns and consumed_pct/flagged/missing_charging_type —
// deriveVehicleMetrics may re-run over a revised prior day (D4's 24h
// overlap) or the vehicle_snapshots row itself may have been replaced
// (telemetry's own same-day UPSERT), so a stale value here must not survive
// a re-derivation. created_at is DELIBERATELY ABSENT from the SET clause —
// it must record when this (account_id, tesla_id, metric_date) was FIRST
// written, not the most recent recompute, mirroring UpsertChargeGap's
// identical convention (internal/telemetry/db/query.sql).
func (q *Queries) UpsertVehicleMetric(ctx context.Context, arg UpsertVehicleMetricParams) error {
	_, err := q.db.Exec(ctx, upsertVehicleMetric,
		arg.AccountID,
		arg.TeslaID,
		arg.MetricDate,
		arg.BatteryLevelPct,
		arg.OdometerKm,
		arg.BatteryRangeKm,
		arg.DistanceTraveledKmCalc,
		arg.BatteryUsedPctCalc,
		arg.KmPerPctCalc,
		arg.EstimatedRangeKmCalc,
		arg.DaysSpannedCalc,
		arg.ConsumedPct,
		arg.Flagged,
		arg.MissingChargingType,
	)
	return err
}

const upsertVehicleMetricWatermark = `-- name: UpsertVehicleMetricWatermark :exec
INSERT INTO vehicle_metric_watermarks (
    account_id, tesla_id, source, source_updated_at
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (account_id, tesla_id, source) DO UPDATE SET
    source_updated_at = EXCLUDED.source_updated_at,
    updated_at         = now()
`

type UpsertVehicleMetricWatermarkParams struct {
	AccountID       uuid.UUID
	TeslaID         int64
	Source          string
	SourceUpdatedAt pgtype.Timestamptz
}

// Advance one source's cursor for one vehicle (design D2/D3/D4). Called by
// Reconcile only for a source whose ...UpdatedSince query returned at least
// one row, advanced to the max UpdatedAt/updated_at observed from that
// source on this run — a source with zero returned rows leaves its
// watermark row untouched (Reconcile's own idempotence contract,
// design.md's Test Contract). created_at is DELIBERATELY ABSENT from the SET
// clause — it must record when this (account_id, tesla_id, source) cursor
// was FIRST created, not the most recent advance, mirroring
// UpsertChargeGap's identical convention.
func (q *Queries) UpsertVehicleMetricWatermark(ctx context.Context, arg UpsertVehicleMetricWatermarkParams) error {
	_, err := q.db.Exec(ctx, upsertVehicleMetricWatermark,
		arg.AccountID,
		arg.TeslaID,
		arg.Source,
		arg.SourceUpdatedAt,
	)
	return err
}

const vehicleMetricsConsumedByVehicleBetween = `-- name: VehicleMetricsConsumedByVehicleBetween :many
SELECT
    metric_date, consumed_pct, distance_traveled_km_calc, flagged,
    missing_charging_type, days_spanned_calc
FROM vehicle_metrics
WHERE account_id  = $1
  AND tesla_id    = $2
  AND metric_date BETWEEN $3 AND $4
  AND battery_used_pct_calc IS NOT NULL
ORDER BY metric_date
`

type VehicleMetricsConsumedByVehicleBetweenParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type VehicleMetricsConsumedByVehicleBetweenRow struct {
	MetricDate             pgtype.Date
	ConsumedPct            pgtype.Float8
	DistanceTraveledKmCalc pgtype.Float8
	Flagged                bool
	MissingChargingType    pgtype.Text
	DaysSpannedCalc        pgtype.Int4
}

// Backs analytics.Reader.ConsumedByDay (design D13). ONE OF TWO SEPARATE
// filtered reads — deliberately NOT a shared unfiltered SELECT with
// OdometerDeltaByVehicleBetween below. The trailing
// "battery_used_pct_calc IS NOT NULL" excludes every predecessor-less row
// (design D9) so this method's output stays characterization-identical to
// today's live deriveConsumedByDay, which never emitted such a row either
// (D5a). The filter column is battery_used_pct_calc, not consumed_pct —
// both are NULL under the identical condition (D9), so either is an
// equivalent predicate; this one is picked because it is the column
// deriveConsumedByDay's own existing D5a check already named. Every row
// that passes this filter is guaranteed (D9's "co-occur" guarantee) to also
// have non-NULL distance_traveled_km_calc/days_spanned_calc, so the Go
// mapping in reader.go needs no nil-check and no fallback-to-1 branch for
// either.
// Served by vehicle_metrics_account_tesla_date_unique's own index (Index
// Plan, read pattern #1) — no separate CREATE INDEX. The IS NOT NULL clause
// is a residual predicate evaluated against the already-tiny (<=
// historyRangeMaxDays = 90 row) range-scanned result.
func (q *Queries) VehicleMetricsConsumedByVehicleBetween(ctx context.Context, arg VehicleMetricsConsumedByVehicleBetweenParams) ([]VehicleMetricsConsumedByVehicleBetweenRow, error) {
	rows, err := q.db.Query(ctx, vehicleMetricsConsumedByVehicleBetween,
		arg.AccountID,
		arg.TeslaID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleMetricsConsumedByVehicleBetweenRow
	for rows.Next() {
		var i VehicleMetricsConsumedByVehicleBetweenRow
		if err := rows.Scan(
			&i.MetricDate,
			&i.ConsumedPct,
			&i.DistanceTraveledKmCalc,
			&i.Flagged,
			&i.MissingChargingType,
			&i.DaysSpannedCalc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vehicleMetricsOdometerByVehicleBetween = `-- name: VehicleMetricsOdometerByVehicleBetween :many
SELECT
    metric_date, odometer_km, distance_traveled_km_calc
FROM vehicle_metrics
WHERE account_id  = $1
  AND tesla_id    = $2
  AND metric_date BETWEEN $3 AND $4
  AND distance_traveled_km_calc IS NOT NULL
ORDER BY metric_date
`

type VehicleMetricsOdometerByVehicleBetweenParams struct {
	AccountID uuid.UUID
	TeslaID   int64
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type VehicleMetricsOdometerByVehicleBetweenRow struct {
	MetricDate             pgtype.Date
	OdometerKm             float64
	DistanceTraveledKmCalc pgtype.Float8
}

// Backs analytics.Reader.OdometerDeltaByDay (design D13). The SECOND of the
// two separate filtered reads (see VehicleMetricsConsumedByVehicleBetween
// above for why these are not merged into one unfiltered query). The
// trailing "distance_traveled_km_calc IS NOT NULL" excludes every
// predecessor-less row for the same reason. OdometerDeltaByDay's
// roadmap-D5 clamp (math.Max(0, ...)) is applied in Go, on this
// already-guaranteed-non-NULL value — never in this query, and never
// against a NULL (the filter guarantees that). The stored column itself
// stays the raw, unclamped value.
// Served by the identical index and residual-predicate reasoning as
// VehicleMetricsConsumedByVehicleBetween above.
func (q *Queries) VehicleMetricsOdometerByVehicleBetween(ctx context.Context, arg VehicleMetricsOdometerByVehicleBetweenParams) ([]VehicleMetricsOdometerByVehicleBetweenRow, error) {
	rows, err := q.db.Query(ctx, vehicleMetricsOdometerByVehicleBetween,
		arg.AccountID,
		arg.TeslaID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleMetricsOdometerByVehicleBetweenRow
	for rows.Next() {
		var i VehicleMetricsOdometerByVehicleBetweenRow
		if err := rows.Scan(&i.MetricDate, &i.OdometerKm, &i.DistanceTraveledKmCalc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
